name: CI - Testes Automatizados

# Define quando o workflow será executado
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o código do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Passo 2: Configurar o Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Passo 3: Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Executar os testes automatizados
      - name: Executar testes
        run: |
          pytest
